id: I0F89AEE5
ocr_import_info:
  timestamp: '2023-06-27T16:25:48.138306+00:00'
  batch_id: batch-0443
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-27 17:02:41.050379+00:00
last_modified: 2023-06-27 17:02:41.050384+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3871
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3871
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་ལ་འཇུག་པ།
  languages:
  - bo
  author: ཟླ་བ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9609538139129242
  ocr_word_median_confidence_index: 0.99529606
bases:
  I1KG3953:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3953
      total_pages: 108
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3953.txt
    statistics:
      ocr_word_median_confidence_index: 0.99529606
      ocr_word_mean_confidence_index: 0.9609538139129242
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
